<?php

namespace CakeDC\Roadrunner\Test\TestCase;

use Cake\Core\Configure;
use Cake\TestSuite\TestCase;
use CakeDC\Roadrunner\Bridge;
use CakeDC\Roadrunner\Exception\CakeRoadrunnerException;
use CakeDC\Roadrunner\Http\ServerRequestFactory;
use Psr\Http\Message\ResponseInterface;

class BridgeTest extends TestCase
{
    private string $rootDir = __DIR__ . '/../test_app';

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Configure::write('Error', []);
        Configure::write('App.namespace', 'App\\');
    }

    public function test_handle(): void
    {
        $response = (new Bridge($this->rootDir))->handle(ServerRequestFactory::fromGlobals());
        $this->assertInstanceOf(ResponseInterface::class, $response);
    }

    public function test_handle_with_trailing_root_directory_slash(): void
    {
        $response = (new Bridge($this->rootDir))->handle(ServerRequestFactory::fromGlobals());
        $this->assertInstanceOf(ResponseInterface::class, $response);
    }

    public function test_construct_throws_exception_when_root_dir_not_found(): void
    {
        $rootDir = '/dev/null/cakephp-roadrunner-'. md5((string)microtime(true));
        $this->expectException(CakeRoadrunnerException::class);
        $this->expectExceptionMessage(sprintf(CakeRoadrunnerException::ROOT_DIR_NOT_FOUND, $rootDir));
        (new Bridge($rootDir));
    }

    /**
     * @todo this is difficult to test
     * @return void
     */
    public function test_construct_throws_exception_when_application_instance_not_created(): void
    {
        $this->markTestSkipped('@todo: difficult to test');
        $this->expectException(CakeRoadrunnerException::class);
        $this->expectExceptionMessage(CakeRoadrunnerException::APP_INSTANCE_NOT_CREATED);
        (new Bridge($this->rootDir));
    }
}