<?php

namespace CakeDC\Roadrunner\Test\TestCase;

use Cake\Core\Configure;
use Cake\TestSuite\TestCase;
use CakeDC\Roadrunner\Bridge;
use CakeDC\Roadrunner\Exception\CakeRoadrunnerException;
use CakeDC\Roadrunner\Test\ServerRequestHelper;

class BridgeTest extends TestCase
{
    private string $rootDir;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Configure::write('Error', []);
        Configure::write('debug', true);
        Configure::write('App.namespace', 'App\\');
        $this->rootDir = dirname(__DIR__ . '../') . '/test_app';
    }

    public function test_handle(): void
    {
        $request = (new ServerRequestHelper())->buildRequest();
        $response = (new Bridge($this->rootDir))->handle($request);
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertEquals(['hello' => 'world'], json_decode((string) $response->getBody(), true));
    }

    public function test_handle_with_trailing_root_directory_slash(): void
    {
        $request = (new ServerRequestHelper())->buildRequest();
        $response = (new Bridge($this->rootDir . '/'))->handle($request);
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertEquals(['hello' => 'world'], json_decode((string) $response->getBody(), true));
    }

    public function test_construct_throws_exception_when_root_dir_not_found(): void
    {
        $rootDir = '/dev/null/cakephp-roadrunner-'. md5((string)microtime(true));
        $this->expectException(CakeRoadrunnerException::class);
        $this->expectExceptionMessage(sprintf(CakeRoadrunnerException::ROOT_DIR_NOT_FOUND, $rootDir));
        (new Bridge($rootDir));
    }

    /**
     * @todo this is difficult to test
     * @return void
     */
    public function test_construct_throws_exception_when_application_instance_not_created(): void
    {
        $this->markTestSkipped('@todo: difficult to test');
        $this->expectException(CakeRoadrunnerException::class);
        $this->expectExceptionMessage(CakeRoadrunnerException::APP_INSTANCE_NOT_CREATED);
        (new Bridge($this->rootDir));
    }
}